version: 2.1

jobs:
  build:
    docker:
      - image: circle/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  
  test:
    docker:
      - image: circle/node:13.8.0
    steps:
    - checkout
    - run: npm i
    - run: npm run test

  analyze:
    docker:
      - image: circle/node:13.8.0
    steps:
      - checkout
      - run: npm run audit

workflows:
  myworkflows:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test



